### ISSUE TITLE
load-generator can not talk to nginx

### ISSUE THREAD

**Issue by pixie79** [PaulMaddox/aws-appmesh-helm#3] opened 2019-05-20 21:49 UTC
I have followed along this demo, however now with everything deployed. Nginx is running and healthy but the loadtest pods are crashing as they can not talk to nginx.

Not sure why not, any ideas?

**Comment by PaulMaddox** [comment] 2019-05-21 06:54
I've seen this once before (out of maybe 50 times deploying this). When it happened to me, it was because Helm had not deployed all of the App Mesh CRDs for some reason.

Please make sure you're using v2.13.1 of Helm (maybe you already had it installed and didn't upgrade), as before this version there was a known bug with CRD installation.

**Comment by karelbemelmans** [comment] 2019-05-23 14:00
I ran the tutorial from scratch today on a newly installed Mac and it all went fine, so I can confirm that it works with the latest helm version.

(except the IAM policy for X-Ray but there is already another ticket for that problem)

**Comment by PaulMaddox** [comment] 2019-05-30 04:10
Closing this for now under the assumption it was caused by an old version of Helm.

**Closed as completed by PaulMaddox** 2019-05-30 04:10 UTC

**Comment by carlosafonso** [comment] 2019-06-25 10:04
Hi @PaulMaddox , not sure if this is exactly the same issue but I cannot get the Load Generator pods to start, even with Helm 2.14.

```
$ helm version

Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

```
$ kubectl get pods -n appmesh-demo

NAME                             READY   STATUS             RESTARTS   AGE
load-generator-cd6999f85-b2pd2   3/4     CrashLoopBackOff   21         84m
load-generator-cd6999f85-rnkd5   3/4     CrashLoopBackOff   21         84m
load-generator-cd6999f85-t6fsp   3/4     CrashLoopBackOff   21         84m
nginx-7ccbd466cf-7rgh5           4/4     Running            0          84m
nginx-7ccbd466cf-ptbcn           4/4     Running            0          84m
```

I'm trying to see the Pod logs but I get this error, although this might just be me doing something absolutely wrong:

```
Error from server (NotFound): pods "load-generator-cd6999f85-b2pd2" not found
```
